### ISSUE TITLE
fail to work on mac(m1)

### ISSUE THREAD

**Issue by Neo-Flash** [longlongman/DESERT#1]
Hi!
Thank u for sharing your excellent work！
when I try to run this on my mac book pro(m1 pro),it just doesn't work
so could u please share a dock file or something can work on mac?
thanks!

**Comment by longlongman** [comment]
I am sorry that the code does not run on your device smoothly. What is the dock file, a docker image, or vina docking results? Would you like to share more specific problems when trying to run the code?

**Comment by Neo-Flash** [comment]
oh sorry
I mean "docker image"
Could  you please share a docker image ? 
so everyone can run your program
Thank you very much!
