### ISSUE TITLE
how to reduce batch size during generation

### ISSUE THREAD

**Issue by orgw** [longlongman/DESERT#5]
hi, my gpu keeps busting up when i'm trying to generate. 

horovodrun -np 8 bycha-run \
    --config configs/generating.yaml \
    --lib shape_pretraining \
    --task.mode evaluate \
    --task.data.train.path data \
    --task.data.valid.path.samples /home/kiwoong/DESERT/data/sample_shapes.pkl \
    --task.data.test.path.samples  /home/kiwoong/DESERT/data/sample_shapes.pkl \
    --task.dataloader.train.max_samples 1 \
    --task.dataloader.valid.sampler.max_samples 1 \
    --task.dataloader.test.sampler.max_samples 1 \
    --task.model.path /home/kiwoong/DESERT/trainer/save_model_dir/1WW_30W_5048064.pt \
    --task.evaluator.save_hypo_dir /home/kiwoong/DESERT/trainer/save_hypo_di

this is the bash file I'm running right now. 
How do you reduce the batch size?? In the config file for generation it seems that the only option is max_sample, which i set to 1 but increases steadily. thanks.

**Comment by longlongman** [comment]
To run the method on GPUs with smaller memory, you need to reduce `num_return_sequence` in the config file. To be specific, when setting the `max_sample` to 1, the batch size is already assigned to 1. However, for each shape, we generate `num_return_sequence` molecules at the same time, which may cause the out-of-memory issue. Therefore, I suggest that you can reduce `num_return_sequence`.

P.s. Also make sure `fnum_return_sequence` <= `num_return_sequence`.

**Comment by orgw** [comment]
longlongman thank you for the quick reply.
